Project_Four/Project_Four/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from appFour import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^appFour/', include('appFour.urls'))
]

Project_Four/appFour/urls.py
from django.conf.urls import url
from appFour import views

app_name = 'appFour'

urlpatterns =[
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

Project_Four/appFour/models.py
from django.db import models

# Create your models here.

Project_Four/appFour/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dic = {'text':'hola mundo', 'number':100}
    return render(request,'appFour/index.html',context=context_dic)

def other(request):
    return render(request,'appFour/other.html')

def relative(request):
    return render(request,'appFour/relative_url.html')

Project_Four/templates/appFour/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a> </li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li><a class="navbar-link" href="{% url 'appFour:other' %}">Other</a> </li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      <!-- Cualquier cosa fuera de este bloque se heredara si se usa extends -->

      {% endblock %}

    </div>

  </body>
</html>

Project_Four/templates/appFour/index.html
<!DOCTYPE html>
{% extends 'appFour/base.html' %}
{% load extras %}

  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is Index.html</h2>

    <h1>{{ text|cut:'hola' }}</h1>
    <h1>{{ number }}</h1>

  {% endblock %}

Project_Four/templates/appFour/other.html
<!DOCTYPE html>
{% extends 'appFour/base.html' %}

  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is other.html</h2>

  {% endblock %}

Project_Four/templates/appFour/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative URL templates</h1>

    <a href="{% url 'appFour:other' %}">Go to Other page</a><br>
    <a href="{% url 'admin:index' %}">Go to Admin</a><br>
    <a href="{% url 'index' %}">Go to Index</a>

  </body>
</html>